apiVersion: v1
kind: Namespace
metadata:
  name: pogokwetter
  labels:
    name: pogokwetter
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: pogokwetter
  labels:
    app: user-service
    tier: backend
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: user-service
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: user-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      containers:
        - name: pokemon-service
          image: ghcr.io/teunbuis-semester6-pogokwetter/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: user-mysql
  namespace: pogokwetter
  labels:
    app: user-mysql
    tier: backend
spec:
  selector:
    app: user-mysql
  ports:
    - protocol: TCP
      name: "3307"
      port: 3307
      targetPort: 3307
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mysql
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: user-mysql
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-mysql
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3308
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Teun
            - name: MYSQL_TCP_PORT
              value: "3308"
            - name: MYSQL_DATABASE
              value: user
---