name: Build-Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Login To Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build User-service Image
        working-directory: ./
        run: docker build -t ${{env.REGISTRY}}/teunbuis-semester6-pogokwetter/user-service:latest .

      - name: Push User-service Image
        working-directory: ./
        run: docker push ${{env.REGISTRY}}/teunbuis-semester6-pogokwetter/user-service:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.3
        with:
          project_id: handy-resolver-384812
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image to GCR
        run: |
          export PROJECT_ID=handy-resolver-384812 
          export IMAGE_NAME=gcr.io/$PROJECT_ID/user-service
          export TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG